# Generated by Django 5.0.5 on 2024-05-07 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_address_person_address_persons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="persons",
        ),
        migrations.AddField(
            model_name="address",
            name="persons",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.person",
            ),
            preserve_default=False,
        ),
    ]
