# Generated by Django 5.0.5 on 2024-05-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_address_persons_address_persons"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="persons",
        ),
        migrations.AddField(
            model_name="address",
            name="persons",
            field=models.ManyToManyField(to="myapp.person"),
        ),
    ]
