# Generated by Django 5.0.5 on 2024-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_remove_address_persons_address_persons"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("account_number", models.CharField(max_length=20, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ifsc_code", models.CharField(max_length=20, unique=True)),
                ("branch", models.CharField(max_length=20)),
                ("persons", models.ManyToManyField(to="myapp.person")),
            ],
        ),
    ]
