# Generated by Django 5.0.5 on 2024-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
